export const ICONS = {
  DASHBOARD: 'tabler:layout-dashboard',
  COMPANY: 'tabler:building',
  EMPLOYEE: 'tabler:users',
  MEMBERSHIP: 'tabler:ticket',
  MEMBERSHIP_SUBMODULE: 'tabler:transform',
  MODULE: 'tabler:apps',
  SUBMODULE: 'tabler:components',
  BASE_PERMISSION: 'tabler:key',
  BASE_ROLE: 'tabler:shield',
  BASE_ROLE_PERMISSION: 'tabler:shield-check',

  ANIMAL_SETTINGS: 'tabler:dog',
  SPECIES: 'tabler:cat',
  BREED: 'tabler:fish',
  COLOR: 'tabler:palette',
  CHEVRON_DOWN: 'tabler:chevron-down',

  CLINICAL_CATALOGS: 'tabler:clipboard-heart',
  CONSULTATION_TYPE: 'tabler:stethoscope',
  VACCINATION_TYPE: 'tabler:vaccine',
  SURGERY_TYPE: 'tabler:scalpel',
  LABORATORY_TEST_TYPE: 'tabler:test-pipe',
  DIAGNOSTIC_IMAGING_TYPE: 'tabler:photo-scan',

  ADD: 'tabler:plus',
  EDIT: 'tabler:pencil',
  DELETE: 'tabler:trash',
  CLOSE: 'tabler:x',
  BACK: 'tabler:arrow-left',
  LOGOUT: 'tabler:logout',

  USER: 'tabler:user',
  LOCK: 'tabler:lock',
  MAIL: 'tabler:mail',
  EYE: 'tabler:eye',
  EYE_OFF: 'tabler:eye-off',

  SEARCH: 'tabler:search',
  BELL: 'tabler:bell',
  PAW: 'tabler:paw',
  ARROW_RIGHT: 'tabler:arrow-right',
  ARROW_UP_RIGHT: 'tabler:arrow-up-right',

  CHEVRON_LEFT: 'tabler:chevron-left',
  CHEVRON_RIGHT: 'tabler:chevron-right',

  SUCCESS: 'tabler:circle-check',
  ERROR: 'tabler:alert-circle',
  WARNING: 'tabler:alert-triangle',
  INFO: 'tabler:info-circle',
  CHECKED: 'tabler:circle-check-filled',
  UNCHECKED: 'tabler:circle',
} as const
