export const ROUTE_NAMES = {
  LOGIN: 'login',
  DASHBOARD: 'dashboard',
  COMPANIES_LIST: 'companies-list',
  COMPANY_DETAIL: 'company-detail',
  MEMBERSHIPS_LIST: 'memberships-list',
  MEMBERSHIP_DETAIL: 'membership-detail',
  MODULES_LIST: 'modules-list',
  MODULE_DETAIL: 'module-detail',
  SUBMODULES_LIST: 'submodules-list',
  SUBMODULE_DETAIL: 'submodule-detail',
  BASE_PERMISSIONS_LIST: 'base-permissions-list',
  BASE_PERMISSION_DETAIL: 'base-permission-detail',
  BASE_ROLES_LIST: 'base-roles-list',
  BASE_ROLE_DETAIL: 'base-role-detail',
  BASE_ROLE_PERMISSIONS_LIST: 'base-role-permissions-list',
  BASE_ROLE_PERMISSION_DETAIL: 'base-role-permission-detail',
  MEMBERSHIP_SUB_MODULES_LIST: 'membership-sub-modules-list',
  MEMBERSHIP_SUB_MODULE_DETAIL: 'membership-sub-module-detail',
} as const
